[debian] backup/copy old confiles to /etc/veraweb
So we need no manual restore of conffiles at
/var/lib/tomcat/webapps/veraweb/OCTOPUS/ after
installing this new package because we do not overwrite it without
testing.

git-svn-id: svn+ssh://evolvis.org/scmrepos/svn/veraweb/trunk@1451 293e2372-0500-4244-b9aa-80dbbde7b6ea

diff --git a/debian/veraweb-java.postinst b/debian/veraweb-java.postinst
--- a/debian/veraweb-java.postinst
+++ b/debian/veraweb-java.postinst
@@ -17,11 +17,24 @@ set -e
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
+INIT="/etc/init.d/tomcat7"
 DBSETUP="/usr/share/veraweb-java/veraweb-dbsetup.sh"
 ADMIN="administrator"
 case "$1" in
     configure)
         ${DBSETUP} -a ${ADMIN}
+
+        # If tomcat is running we do a restart to renew all configs and apps.
+        # After the restart tomcat needs a notifier on it's war files to do the
+        # update, we wait a bit before we touch them to be sure tomcat gets it's
+        # notifier up.
+        if ${INIT} status > /dev/null; then
+            (${INIT} restart && sleep 5) && \
+            touch /usr/share/maven-repo/org/evolvis/veraweb/veraweb-war/veraweb.war || \
+            echo "Warning can't restart tomcat."
+        else
+            ${INIT} start || echo "Warning: can't start tomcat. Please resove it manually."
+        fi
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
